pipeline {
    agent any

    tools {
        maven 'localMaven' 
    }

    parameters {
         string(name: 'tomcat_dev', defaultValue: '3.131.133.139', description: 'Staging Server')
         string(name: 'tomcat_prod', defaultValue: '18.117.182.102', description: 'Production Server')
    }

    
stages{
        stage('Build'){

            steps {
                sh 'mvn clean package'
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }

        stage ('Deployments'){
            parallel{
                stage ('Deploy to Staging'){
                    steps {
                        sh "scp -i /code/tomcat-demo.pem **/target/*.war ec2-user@${params.tomcat_dev}:/var/lib/tomcat/webapps"
                    }
                }

                stage ("Deploy to Production"){
                    steps {
                        sh "scp -i /code/tomcat-demo.pem **/target/*.war ec2-user@${params.tomcat_prod}:/var/lib/tomcat/webapps"
                    }
                }
            }
        }
    }
}