pipeline {
    agent none

    tools {
        maven 'localMaven' 
    }

    parameters {
         string(name: 'tomcat_dev', defaultValue: '3.21.97.6', description: 'Staging Server')
         string(name: 'tomcat_prod', defaultValue: '18.224.63.87', description: 'Production Server')
         string(name: 'jenkins_home', defaultValue: '/home/jenkins', description: 'jenkins home on slave')
    }

    
stages{
        stage('Build'){
            agent {label 'master'}
            steps {
                sh 'mvn clean package'
            }
            post {
                success {
                    echo 'Now Archiving...'
                    archiveArtifacts artifacts: '**/target/*.war'
                }
            }
        }

        stage ('Deployments'){
            
            parallel{
                stage ('Deploy to Staging'){
                    agent {label 'aws-client'}
                    steps {
                        echo 'PRIMA DI SCP'
                        sh "pwd"
                        copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: '${JOB_NAME}', selector: specific('${BUILD_NUMBER}'), target: '.'
                        sh "scp -i ${params.jenkins_home}/.ssh/tomcat-demo.pem **/target/*.war ec2-user@${params.tomcat_dev}:/var/lib/tomcat/webapps"
                    }
                }

                stage ("Deploy to Production"){
                    agent {label 'aws-client'}
                    steps {
                        echo 'PRIMA DI SCP'
                        sh "pwd"
                        copyArtifacts filter: '**/*.war', fingerprintArtifacts: true, projectName: '${JOB_NAME}', selector: specific('${BUILD_NUMBER}'), target: '.'
                        sh "scp -i ${params.jenkins_home}/.ssh/tomcat-demo.pem **/target/*.war ec2-user@${params.tomcat_prod}:/var/lib/tomcat/webapps"
                    }
                }
            }
        }
    }
}